{ config, lib, pkgs, ... }:

{
  # Enable ragenix secrets management
  # Secrets are decrypted at runtime to /run/agenix/<secret-name>
  # Access them using: config.age.secrets.<secret-name>.path
  
  age.secrets = {
    # System settings exports (auto-generated by export scripts)
    # These are created and encrypted by settings/gnome-export.sh or settings/darwin-export.sh
    
    # GNOME dconf settings (Linux only)
    gnome-dconf-settings = {
      file = ../secrets/gnome-dconf-settings.age;
      mode = "0440";
    };
    
    # macOS defaults settings (macOS only)
    darwin-defaults-settings = {
      file = ../secrets/darwin-defaults-settings.age;
      mode = "0440";
    };
    
    # Network credentials
    wifi-home = {
      file = ../secrets/wifi-home.age;
      mode = "0440";
    };
  };
  
  # Example: How to use secrets in configuration
  # 
  # For services that need a password file:
  # services.someService = {
  #   enable = true;
  #   passwordFile = config.age.secrets.service-password.path;
  # };
  #
  # For environment variables:
  # systemd.services.myservice.environment = {
  #   API_TOKEN_FILE = config.age.secrets.api-token.path;
  # };
  #
  # For reading in scripts:
  # script = ''
  #   API_KEY=$(cat ${config.age.secrets.api-token.path})
  #   # use $API_KEY
  # '';
  #
  # For importing decrypted Nix files (like settings exports):
  # imports = [ config.age.secrets.gnome-dconf-settings.path ];
}
