# This file will be generated by nixos-generate-config
# Run this command on your server:
#   sudo nixos-generate-config --show-hardware-config > hosts/server/hardware-configuration.nix
#
# This is a placeholder file. Replace it with the actual hardware configuration
# generated on your target server machine.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # Replace this entire file with output from:
  # sudo nixos-generate-config --show-hardware-config

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
