{ config, pkgs, lib, ... }:

let
  cfg = import ../../settings/config.nix;
in
{
  # ─── Import auto-exported dconf settings ─────────────────────────────────────
  # settings/gnome/dconf-settings.nix is generated by settings/gnome-export.sh
  # and contains the full dconf state from your last export.
  # Values below override or supplement it with config-driven values.
  imports = [
    ../../settings/gnome
  ];

  # ─── GNOME extension packages ────────────────────────────────────────────────
  # Package list driven from settings/config/desktop.nix → gnome.extensionPackages
  home.packages =
    map (name: pkgs.gnomeExtensions.${name}) cfg.desktop.gnome.extensionPackages;

  # ─── Config-derived dconf overrides ──────────────────────────────────────────
  # Only keys that should track settings/config values live here.
  # Detailed extension preferences (layouts, colours, etc.) live in
  # settings/gnome/dconf-settings.nix (auto-generated — do not edit by hand).
  dconf.settings = {

    # Wallpaper – tracks the wallpapers/wallpaper.jpg in this repo
    "org/gnome/desktop/background" = {
      picture-uri      = "file://${../../wallpapers/wallpaper.jpg}";
      picture-uri-dark = "file://${../../wallpapers/wallpaper.jpg}";
      picture-options  = "zoom";
    };

    # Theme + monospace font – driven from settings/config/desktop.nix
    "org/gnome/desktop/interface" = {
      gtk-theme           = cfg.desktop.theme;
      icon-theme          = cfg.desktop.iconTheme;
      color-scheme        = "prefer-dark";
      monospace-font-name = cfg.desktop.monoFont;
    };

    # GNOME Console font – driven from settings/config/desktop.nix
    "org/gnome/Console" = {
      custom-font      = cfg.desktop.monoFontConsole;
      use-system-font  = false;
    };

    # Enabled extensions – driven from settings/config/desktop.nix
    "org/gnome/shell" = {
      disable-user-extensions = false;
      enabled-extensions      = cfg.desktop.gnome.enabledExtensions;
    };
  };
}
